name: ApiPdf
version: 1.0.0
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  http: ^1.1.0
  http_server: ^1.0.0
  intl: ^0.18.1
  pdf: ^3.10.4
  shelf: ^1.2.0
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0